### ISSUE TITLE
알림에 읽음 여부 필드 추가 및 읽음 처리 로직 만들기!!

### ISSUE THREAD

**Issue by wocjf0513** [SCBJ-7/SCBJ-BE#159]
# 😀 motivation
> 알림 기획이 fix됨에 따라, 읽지 않은 알림이 있는지 인디케이터를 통해 보여줄 수 있어야 합니다! 그렇기 때문에 알림에는 읽음 여부 필드가 필요하고 알림 조회 시, 읽음 여부를 처리할 수 있는 로직을 만들고자 합니다.
# 😄 modification
- [ ] 알림 조회 API 수정 (조회 시, 알림 읽음 여부를 체크)
- [ ] 알림에 읽음 여부 필드 추가
- [ ] 테스트 수정

# 😗 etc
[알림 기획](https://www.notion.so/8e70a69e6c164af785f570338d18b319)

**Comment by YurimYang** [comment]
이슈 확인했습니다 !
